// Derives the package's public surface from the source tree, then writes both
// the root barrel and the `exports` map in package.json.
//
// Generated rather than hand-written because there are ~100 entries and a
// hand-maintained map drifts from the tree the first time a file is added.
//
// `INTERNAL` is the triage list: modules that exist to serve the components and
// whose names appear in no public prop type. Anything not listed is a semver
// commitment, so adding to this list is the cheap direction and removing from
// it is the expensive one.
//
// `BARREL_EXCLUDED` is a different thing and must not be confused with it: these
// modules are fully public and keep their subpath, they are just kept *out of
// the root barrel*. A module that statically imports an optional peer
// dependency cannot be re-exported from `index.ts`, because the barrel is one
// module — importing anything from the root would load it and crash for every
// consumer who did not install that peer. This is the whole reason the DataPort
// seam and its TanStack adapter are separate files, and `dep-guard` enforces
// the property independently.
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const ROOT = new URL("..", import.meta.url).pathname;
const SRC = join(ROOT, "src");

const INTERNAL = new Set(["lib/chart-geometry", "lib/step-graph-layout"]);
const BARREL_EXCLUDED = new Set(["lib/tanstack-data-port"]);

const walk = (dir) =>
  readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry);
    return statSync(path).isDirectory() ? walk(path) : [path];
  });

const modules = walk(SRC)
  .filter((path) => /\.tsx?$/.test(path))
  .map((path) => relative(SRC, path).replace(/\.tsx?$/, ""))
  .filter(
    (id) =>
      id !== "index" &&
      !INTERNAL.has(id) &&
      // Test modules never join the published surface — shipping them through
      // the barrel makes every consumer load them, and bun test discovers the
      // dist *.test.js files as runnable suites.
      !/\.test$/.test(id) &&
      !/(^|\/)test\//.test(id),
  )
  .sort();

const exportsMap = {
  ".": { types: "./dist/index.d.ts", default: "./dist/index.js" },
  "./styles.css": "./dist/styles.css",
  "./theme.css": "./dist/theme.css",
  "./package.json": "./package.json",
};
for (const id of modules) {
  exportsMap[`./${id}`] = { types: `./dist/${id}.d.ts`, default: `./dist/${id}.js` };
}

const pkgPath = join(ROOT, "package.json");
const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
pkg.exports = exportsMap;
writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);

const barrelModules = modules.filter((id) => !BARREL_EXCLUDED.has(id));

const barrel = [
  "// Generated by scripts/generate-exports.mjs. Do not edit.",
  "//",
  "// Re-exports only, and the package is sideEffects-free, so importing from",
  "// the root still tree-shakes down to what you used.",
  "//",
  "// Modules that statically import an optional peer dependency are absent here",
  "// on purpose and must be imported by their subpath. The barrel is a single",
  "// module: anything it re-exports is loaded by any root import, so one such",
  "// re-export would make the optional peer mandatory for everyone.",
  ...[...BARREL_EXCLUDED].sort().map((id) => `//   @corbits/react-ui/${id}`),
  "",
  ...barrelModules.map((id) => `export * from "./${id}.js";`),
  "",
].join("\n");
writeFileSync(join(SRC, "index.ts"), barrel);

console.log(
  `generate-exports: ${modules.length} public modules ` +
    `(${INTERNAL.size} internal, ${BARREL_EXCLUDED.size} subpath-only)`,
);
